_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 53
                - 55
            "2":
                - 1
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
G:
    value: 1
architecture:
    value: diverse
batch-size:
    value: 32
batch-time:
    value: 32
dataset:
    value: threebody
dim:
    value: 12
epochs:
    value: 1000
eval:
    value: 3
learning_rate:
    value: 0.001
m1:
    value: 1
m2:
    value: 1
m3:
    value: 1
phi_span:
    value:
        - 0
        - 1
test:
    value: 3
timepoints:
    value: 128
train:
    value: 30
type:
    value: fig8
warmup:
    value: 0
