_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 53
                - 55
            "2":
                - 1
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
G:
    value: 1
architecture:
    value: diverse
batch-size:
    value: 32
batch-time:
    value: 32
cuda:
    value: true
dataset:
    value: twobody
dim:
    value: 8
epochs:
    value: 1000
eval:
    value: 3
learning_rate:
    value: 0.001
m1:
    value: 1
m2:
    value: 3
r1_span:
    value:
        - 1
        - 5
test:
    value: 3
timepoints:
    value: 128
train:
    value: 30
warmup:
    value: 0
