_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 53
                - 55
            "2":
                - 1
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
H_span:
    value:
        - 5
        - 15
architecture:
    value: diverse
batch-size:
    value: 32
batch-time:
    value: 32
cuda:
    value: true
dataset:
    value: oscilator
dim:
    value: 2
epochs:
    value: 10
eval:
    value: 3
k:
    value: 0.8
learning_rate:
    value: 0.001
m:
    value: 1
test:
    value: 3
timepoints:
    value: 128
train:
    value: 30
warmup:
    value: 0
