learning_rate: 0.001
architecture: diverse
dataset: oscilator
dim: 2
k: 0.8
m: 1
epochs: 1000 #200
warmup: 0
batch-size: 32 #8
batch-time: 32 #64
train: 30
test: 3
eval: 3
timepoints: 128
H_span: 
  - 5
  - 15
