save : False
dt: 0.1
samples: 7
alpha : 0.261799  # 15 deg
cuda: False # server False

monitoring: False

sbatch: 32
tbatch: 32
lr: 0.001
bias: False
nodes: 3
no_loops: True
sob:
  - 1.0 #0.15 # H
  - 1.0 # q, p
  - 1.0 #0.5 # dq,dp

layer: GAT
size: 128
e_size: 16

train_break: -1
test_break: -1

epochs: 300
sim_type: dat_fig

max_sim_time: 172800 # 2 days

wandb: False
