save : False
dt: 0.1
samples: 3
alpha : 0.261799  # 15 deg
cuda: True # server False

monitoring: False

sbatch: 32
tbatch: 32
lr: 0.001
bias: False
nodes: 3
no_loops: True
sob:
  - 0.15 # H
  - 1.0 # q, p
  - 0.5 # dq,dp

layer: GAT
size: 128
e_size: 16

train_break: -1
test_break: -1

epochs: 100
sim_type: dat_fig

max_sim_time: 60000000 # 3 days

wandb: False